#!/bin/bash

set -e

ln -sfn "$HOME/.dotfiles/bash/bashrc" "$HOME/.bashrc"
ln -sfn "$HOME/.dotfiles/bash/bash_login" "$HOME/.bash_login"
ln -sfn "$HOME/.dotfiles/bash/bash_logout" "$HOME/.bash_logout"
ln -sfn "$HOME/.dotfiles/dig/digrc" "$HOME/.digrc"
ln -sfn "$HOME/.dotfiles/forward/forward" "$HOME/.forward"
ln -sfn "$HOME/.dotfiles/gem/gemrc" "$HOME/.gemrc"
ln -sfn "$HOME/.dotfiles/git/gitattributes" "$HOME/.gitattributes"
ln -sfn "$HOME/.dotfiles/git/gitconfig" "$HOME/.gitconfig"
ln -sfn "$HOME/.dotfiles/input/inputrc" "$HOME/.inputrc"
ln -sfn "$HOME/.dotfiles/lldb/lldbinit" "$HOME/.lldbinit"
ln -sfn "$HOME/.dotfiles/plan/plan" "$HOME/.plan"
ln -sfn "$HOME/.dotfiles/screen/screenrc" "$HOME/.screenrc"
ln -sfn "$HOME/.dotfiles/sqlite/sqliterc" "$HOME/.sqliterc"
ln -sfn "$HOME/.dotfiles/vim/vimrc" "$HOME/.vimrc"

# ssh
if [ -f "$HOME/.dotfiles/local/dotfiles/ssh_config" ]; then
    mkdir -p "$HOME/.ssh"
    rm -f "$HOME/.ssh/config"
    cat "$HOME/.dotfiles/ssh/ssh_config" "$HOME/.dotfiles/local/dotfiles/ssh_config" > "$HOME/.ssh/config"
else
    mkdir -p "$HOME/.ssh"
    ln -sfn "$HOME/.dotfiles/ssh/config" "$HOME/.ssh/ssh_config"
fi

# subversion
mkdir -p "$HOME/.subversion"
ln -sfn "$HOME/.dotfiles/subversion/subversion_config" "$HOME/.subversion/config"

# vim
mkdir -p "$HOME/.vim"
ln -sfn "$HOME/.dotfiles/vim/autoload" "$HOME/.vim/autoload"
ln -sfn "$HOME/.dotfiles/vim/colors" "$HOME/.vim/colors"
ln -sfn "$HOME/.dotfiles/vim/doc" "$HOME/.vim/doc"
ln -sfn "$HOME/.dotfiles/vim/plugin" "$HOME/.vim/plugin"

# Xcode
if [ "$(uname -s)" = "Darwin" -a -x "$(which xcode-select 2>/dev/null)" ]; then
    mkdir -p "$HOME/Library/Developer/Xcode/UserData/FontAndColorThemes"
    ln -sfn "$HOME/.dotfiles/xcode/Tomorrow-Night.dvtcolortheme" "$HOME/Library/Developer/Xcode/UserData/FontAndColorThemes/Tomorrow-Night.dvtcolortheme"
fi

# Mac OS X defaults
if [ "$(uname -s)" = "Darwin" ]; then
    source "$HOME/.dotfiles/defaults/defaultsrc"
fi
