#!/bin/bash

function cd() {
    directory=$@

    if [ "$directory" != ".." ]; then
        if [[ $CDMAP =~ (^|;)${directory}:([^;]*)(;|$) ]]; then
            directory=${BASH_REMATCH[2]}
        fi
    fi

    if [ -z "$directory" ]; then
        builtin cd "$HOME"
    else
        builtin cd "$directory"
    fi
}
