#!/bin/bash

function colors() {
    print_label "Black"
    print_black "normal=[0;30m"
    print_black_bold "bold=[1;30m"
    print_on_black "background=[0;40m"
    print_newline

    print_label "Red"
    print_red "normal=[0;31m"
    print_red_bold "bold=[1;31m"
    print_on_red "background=[0;41m"
    print_newline

    print_label "Green"
    print_green "normal=[0;32m"
    print_green_bold "bold=[1;32m"
    print_on_green "background=[0;42m"
    print_newline

    print_label "Yellow"
    print_yellow "normal=[0;33m"
    print_yellow_bold "bold=[1;33m"
    print_on_yellow "background=[0;43m"
    print_newline

    print_label "Blue"
    print_blue "normal=[0;34m"
    print_blue_bold "bold=[1;34m"
    print_on_blue "background=[0;44m"
    print_newline

    print_label "Magenta"
    print_magenta "normal=[0;35m"
    print_magenta_bold "bold=[1;35m"
    print_on_magenta "background=[0;45m"
    print_newline

    print_label "Cyan"
    print_cyan "normal=[0;36m"
    print_cyan_bold "bold=[1;36m"
    print_on_cyan "background=[0;46m"
    print_newline

    print_label "Gray"
    print_gray "normal=[0;37m"
    print_gray_bold "bold=[1;37m"
    print_on_gray "background=[0;47m"
    print_newline
}
