#!/bin/bash

if [ "$(uname -s)" != "Darwin" ]; then
    return
fi

function console() {
    if [ $# -gt 0 ]; then
        for i in "$@"; do
            if [ -f "$i" ]; then
                echo open -a "Console" "$i"
            else
                echo "$FUNCNAME: $i: No such file"
            fi
        done
    else
        open -a "Console" -f
    fi
}
