#!/bin/bash

function console() {
    if [ "$(uname -s)" != "Darwin" ]; then
        echo "$FUNCNAME: Console: No such application"
        return
    fi

    if [ $# -gt 0 ]; then
        for i in "$@"; do
            if [ -f "$i" ]; then
                echo open -a "Console" "$i"
            else
                echo "$FUNCNAME: $i: No such file"
            fi
        done
    else
        open -a "Console" -f
    fi
}
