#!/bin/bash

function ff() {
    name="$@"

    if [ -z "$name" ]; then
        echo "Usage: $FUNCNAME <name>"
        return
    fi

    find . -iname "*$name*"
}

function ffd() {
    name="$@"

    if [ -z "$name" ]; then
        echo "Usage: $FUNCNAME <name>"
        return
    fi

    find . -iname "*$name*" -type d
}

function ffx() {
    name="$@"

    if [ -z "$name" ]; then
        echo "Usage: $FUNCNAME <name>"
        return
    fi

    find . -iname "*$name*" -type f -perm +111
}
