#!/bin/bash

function grepar() {
    if [ -x "$(which pcre2grep 2>/dev/null)" ]; then
        echo "$FUNCNAME: Use \"greppar\""
        return
    fi

    pattern="$1"
    archives="${@:2}"

    if [ -z "$pattern" -o -z "$archives" ]; then
        echo "Usage: $FUNCNAME <pattern> <archive> [<archive> ...]"
        return
    fi

    lsar $archives | grep "$pattern"
}
