#!/bin/bash

function greppar() {
    if [ ! -x "$(which pcre2grep 2>/dev/null)" ]; then
        echo "$FUNCNAME: Use \"grepar\""
        return
    fi

    pattern="$1"
    archives="${@:2}"

    if [ -z "$pattern" -o -z "$archives" ]; then
        echo "Usage: $FUNCNAME <pattern> <archive> [<archive> ...]"
        return
    fi

    lsar $archives | grepp "$pattern"
}
