#!/bin/bash

if [ ! -x "$(which pcre2grep 2>/dev/null)" ]; then
    echo "warning: 'greppar' is not available, use 'grepar' instead"
    return
fi

function greppar() {
    pattern="$1"
    archive="$2"

    if [ -z "$pattern" -o -z "$archive" ]; then
        echo "Usage: greppar <pattern> <archive>"
        return
    fi

    lsar "$archive" | grepp "$pattern"
}
