#!/bin/bash

function help() {
    print_label "Shell"
    print_magenta_bold "resource" "lsalias" "lsenv" "lsfunction" "rmalias" "rmenv" "rmfunction"

    if [ -x "$(which osascript)" ]; then
        print_magenta_bold "xcd"
    fi

    print_newline

    print_label "File"
    print_magenta_bold "rename" "lsdump" "\n"
    print_label "Directory List"
    print_magenta_bold "ll" "la" "\n"
    print_label "Directory Tree"
    print_magenta_bold "fl" "fld" "flx" "\n"
    print_label "Directory Find"
    print_magenta_bold "ff" "ffd" "ffx" "\n"
    print_label "Process"
    print_magenta_bold "psc" "psa" "psg" "\n"
    print_label "Archive List"
    print_magenta_bold "lsar" "\n"
    print_label "Archive Pack"
    print_magenta_bold "tgz" "\n"

    print_label "Archive Unpack"
    print_magenta_bold "untgz" "untbz" "untar"

    if [ -x "$(which unrar 2>/dev/null)" ]; then
        print_magenta_bold "unrar"
    fi

    print_newline

    print_label "Grep"
    print_magenta_bold "grepp" "greppar" "greppcode" "\n"
    print_label "Sed"
    print_magenta_bold "replace" "\n"
    print_label "Git"
    print_magenta_bold "u=pullall" "b=branch" "m=mergenoff" "p=pushall" "\n"
    print_label "Git"
    print_magenta_bold "a=stage" "aa=stageall" "u=unstage" "c=checkin" "\n"
    print_label "Git"
    print_magenta_bold "l=log" "ll=loglong" "d=diff" "dr=diffraw" "ds=diffstaged" "\n"
    print_label "Git"
    print_magenta_bold "v=viconfig" "\n"

    if [ -x "$(which jq 2>/dev/null)" ]; then
        print_label "JSON"
        print_magenta_bold "jq" "\n"
    fi

    if [ "$(uname -s)" = "Darwin" ]; then
        print_label "Mac OS X"
        print_magenta_bold "console" "plxml" "pljson" "trash" "\n"
    fi

    if [ -x "$(which hfsdata 2>/dev/null)" ]; then
        print_label "HFS Write"
        print_magenta_bold "setcomment" "setlabel" "settype" "setcreator" "sethidden" "setunhidden" "\n"
        print_label "HFS Read"
        print_magenta_bold "lscomment" "lslabel" "lskind" "lstype" "lscreator" "\n"
    fi

    for i in $(echo "$CDMAP" | perl -ne 'print join("\n", split(";"));' | sort); do
        shortcut=$(echo "$i" | cut -d ":" -f1)
        directory=$(echo "$i" | cut -d ":" -f2)

        print_label "Directory"
        print_green "\"$shortcut\"" "$directory" "\n"
    done

    print_label "Prompt"
    print_blue "*unstaged" "+staged" "<behind" ">ahead" "=sync" "\n"
}
