#!/bin/bash

function lsalias() {
    if [ $# -eq 1 ]; then
        alias "$1" | replace "s/^alias $1='//" | replace "s/'$//"
    elif [ $# -eq 0 ]; then
        alias -p | replace 's/^alias //' | sort
    else
        echo "Usage: $FUNCNAME [<alias>]"
    fi
}
