#!/bin/bash

function lsar() {
    if [ $# -eq 0 ]; then
        echo "Usage: $FUNCNAME <archive> [<archive> ...]"
        return
    fi

    for i in "$@"; do
        if [ -f "$i" ]; then
            if [ $# -gt 1 ]; then
                pattern='s/^(\(for architecture \w+\):)?(.+?):(.+?): (.+?)$/$2 $3 $4/'
            else
                pattern='s/^(\(for architecture \w+\):)?(.+?):(.+?): (.+?)$/$3 $4/'
            fi

            nm -A "$i" 2>/dev/null | replace "$pattern" | c++filt
        else
            echo "$FUNCNAME: $i: No such file"
        fi
    done
}
