#!/bin/bash

function lsenv() {
    if [ $# -eq 1 ]; then
        env | grepp "^$1=" | replace "s/^$1=//"
    elif [ $# -eq 0 ]; then
        env | sort
    else
        echo "Usage: $FUNCNAME [<variable>]"
    fi
}
