#!/bin/bash

function lsfunction() {
    if [ $# -eq 1 ]; then
        declare -f "$1"
    elif [ $# -eq 0 ]; then
        declare -F | replace 's/^declare -f //' | sort
    else
        echo "Usage: $FUNCNAME [<function>]"
    fi
}
