#!/bin/bash

function pljson() {
    if [ ! -x "$(which plutil 2>/dev/null)" ]; then
        echo "$FUNCNAME: plutil: No such command"
        return
    fi

    if [ $# -gt 0 ]; then
        for i in "$@"; do
            if [ -f "$i" ]; then
                plutil -convert json -o - "$i"
            else
                echo "$FUNCNAME: $i: No such file"
            fi
        done
    else
        plutil -convert json -o - -
    fi
}
