#!/bin/bash

function pljson() {
    if [ ! -x "$(which plutil 2>/dev/null)" ]; then
        echo "$FUNCNAME: plutil: No such command"
        return
    fi

    plists="$@"

    if [ -z "$plists" ]; then
        plists="-"
    fi

    for i in $plists; do
        if [ -f "$i" -o "$i" = "-" ]; then
            plutil -convert json -o - "$i"
        else
            echo "$FUNCNAME: $i: No such file"
        fi
    done
}
