#!/bin/bash

function print_label() {
    printf "%-18s" "$1"
}

function print_newline() {
    printf "\n"
}

function print_black() {
    _print_escapecode "0" "30" $@
}

function print_black_bold() {
    _print_escapecode "1" "30" $@
}

function print_on_black() {
    _print_escapecode "0" "40" $@
}

function print_red() {
    _print_escapecode "0" "31" $@
}

function print_red_bold() {
    _print_escapecode "1" "31" $@
}

function print_on_red() {
    _print_escapecode "0" "41" $@
}

function print_green() {
    _print_escapecode "0" "32" $@
}

function print_green_bold() {
    _print_escapecode "1" "32" $@
}

function print_on_green() {
    _print_escapecode "0" "42" $@
}

function print_yellow() {
    _print_escapecode "0" "33" $@
}

function print_yellow_bold() {
    _print_escapecode "1" "33" $@
}

function print_on_yellow() {
    _print_escapecode "0" "43" $@
}

function print_blue() {
    _print_escapecode "0" "34" $@
}

function print_blue_bold() {
    _print_escapecode "1" "34" $@
}

function print_on_blue() {
    _print_escapecode "0" "44" $@
}

function print_magenta() {
    _print_escapecode "0" "35" $@
}

function print_magenta_bold() {
    _print_escapecode "1" "35" $@
}

function print_on_magenta() {
    _print_escapecode "0" "45" $@
}

function print_cyan() {
    _print_escapecode "0" "36" $@
}

function print_cyan_bold() {
    _print_escapecode "1" "36" $@
}

function print_on_cyan() {
    _print_escapecode "0" "46" $@
}

function print_gray() {
    _print_escapecode "0" "37" $@
}

function print_gray_bold() {
    _print_escapecode "1" "37" $@
}

function print_on_gray() {
    _print_escapecode "0" "47" $@
}

function _print_escapecode() {
    startcode="\e[$1;$2m"
    stopcode="\e[0m"

    for i in ${@:3}; do
        if [ "$i" = "\n" ]; then
            printf "\n"
        else
            printf "$startcode%s$stopcode " "$i"
        fi
    done
}
