#!/bin/bash

function ql() {
    if [ ! -x "$(which qlmanage 2>/dev/null)" ]; then
        echo "$FUNCNAME: qlmanage: No such command"
        return
    fi

    if [ $# -eq 0 ]; then
        echo "Usage: $FUNCNAME <file> [<file> ...]"
        return
    fi

    qlmanage -p $@ >/dev/null 2>&1 &
}
