" Setup
set nocompatible
set encoding=utf-8
set fenc=utf-8
set termencoding=utf-8
set ttyfast

" Colors
set background=light
set t_Co=256
colorscheme Tomorrow-Night

" Behaviour
set writebackup
set backupdir=~/.vimtmp/backup
set undofile
set undodir=~/.vimtmp/undo
set directory=~/.vimtmp/swap

" Display
set display=lastline
set laststatus=2
set noshowmode
set noruler
set title
set titlestring=%t
set number
set numberwidth=5
set shortmess=atToOI

" Editing
set showmatch
set showcmd
set scrolloff=4
set whichwrap=<,>,[,]
set matchpairs+=<:>
set backspace=eol,start,indent

" Completion
set wildmenu
set wildmode=list:longest

" Indentation
set expandtab
set shiftwidth=4
set softtabstop=4
set shiftround
set formatoptions=tcrqn

" Searching
set ignorecase
set smartcase
set incsearch
set hlsearch

" Syntax
syntax on
filetype on
filetype indent on
filetype plugin on

" Key Bindings
let mapleader=","
noremap <Space> <PageDown>
noremap <BS> <PageUp>
noremap <Up> gk
noremap <Down> gj
noremap m ]m
noremap M [m
noremap ' :call NERDComment(0, "toggle")<CR>
noremap ä >>
noremap ö <<
noremap å =<CR>
noremap U :redo<CR>

" sudo
cmap w! %!sudo tee >/dev/null %

" Line Position
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g'\"" | endif

" Status Line
let g:lightline = {
    \ 'colorscheme': 'jellybeans',
    \ 'component': {
    \   'readonly': '%{&readonly?"x":""}',
    \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}'
    \   },
    \ 'separator': { 'left': '', 'right': '' },
    \ 'subseparator': { 'left': '|', 'right': '|' },
    \ }
