" Setup
set encoding=utf-8
set termencoding=utf-8
set ttyfast

" Colors
set background=light
set t_Co=256
colorscheme Tomorrow-Night

" Behaviour
set writebackup
set backupdir=~/.vimtmp/backup
set undofile
set undodir=~/.vimtmp/undo
set directory=~/.vimtmp/swap

" Display
set display=lastline
set laststatus=2
set noshowmode
set noruler
set title
set titlestring=%m\ %{v:progname}\ %f
set number
set numberwidth=5
set shortmess=atToOI
set cursorline

" Editing
set showmatch
set showcmd
set scrolloff=4
set whichwrap=<,>,[,]
set matchpairs+=<:>
set backspace=eol,start,indent

" Completion
set wildmenu
set wildmode=list:longest
set wildignore+=.git,.svn,.DS_Store,*.o

" Indentation
set expandtab
set shiftwidth=4
set softtabstop=4
set shiftround
set formatoptions=tcrqn

" Searching
set ignorecase
set smartcase
set hlsearch

" Syntax
syntax on
filetype on
filetype indent on
filetype plugin on

" Command Mode Key Bindings
cnoremap w!! w !sudo tee >/dev/null %

" Operator Key Bindings
onoremap 0 ^
onoremap = $
onoremap m ]m
onoremap M [m

" Normal Mode Key Bindings
nnoremap <silent> & :nohlsearch<CR>
nnoremap U :redo<CR>
nnoremap s :w<cr>

nnoremap <Space> <PageDown>
nnoremap <BS> <PageUp>
nnoremap <Up> gk
nnoremap <Down> gj

nnoremap 0 ^
nnoremap = $
nnoremap m ]m
nnoremap M [m

nnoremap <CR> o<Esc>
nnoremap ä >>
nnoremap ö <<
nnoremap å ==
nnoremap <silent> * :let stay_star_view=winsaveview()<CR>*:call winrestview(stay_star_view)<CR>
nnoremap <silent> ' :call NERDComment(0, "toggle")<CR>
nnoremap S i<CR><ESC>^
nnoremap J mzJ`z
nnoremap qw mzguiw`z
nnoremap qW mzgUiw`z
nnoremap qq mzguu`z
nnoremap qQ mzgUU`z

nnoremap q <nop>
nnoremap Q <nop>
nnoremap >> <nop>
nnoremap << <nop>

" Remember Line Position
au BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   execute "normal g'\"" |
    \ endif

" LightLine
let g:lightline = {
    \ 'colorscheme': 'jellybeans',
    \ 'component': {
    \   'readonly': '%{&readonly?"x":""}',
    \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}'
    \   },
    \ 'separator': { 'left': '', 'right': '' },
    \ 'subseparator': { 'left': '|', 'right': '|' },
    \ }
