" Behaviour
set nocompatible
set autowrite
set backupcopy=yes
set clipboard=unnamed
set ttyfast

" Interface
syntax on
set noshowmode
set showmatch
set showcmd
set ruler
set number
set numberwidth=5
set title
set scrolloff=3

" Formatting
set expandtab
set shiftwidth=4
set softtabstop=4
set shiftround
set formatoptions=tcrqn
filetype on
filetype indent on
filetype plugin on
colorscheme Tomorrow-Night

" Searches
set ignorecase
set smartcase
set gdefault
set hlsearch

" Key mappings
set whichwrap=<,>,[,]
set matchpairs+=<:>
set backspace=eol,start,indent
let mapleader=","

noremap <Space> <PageDown>
noremap <BS> <PageUp>
noremap - <PageUp>

nnoremap <C-N> :next<CR>
nnoremap <C-P> :prev<CR>

" Remember line position
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g'\"" | endif

" Status line
set laststatus=2

let g:lightline = {
    \ 'colorscheme': 'jellybeans',
    \ 'component': {
    \   'readonly': '%{&readonly?"x":""}',
    \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}'
    \   },
    \ 'separator': { 'left': '', 'right': '' },
    \ 'subseparator': { 'left': '|', 'right': '|' },
    \ }
