#!/bin/bash

# Expand save panels by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panels by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Disable smart quotes and dashes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable auto correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# Make hidden applications translucent in Dock
defaults write com.apple.dock showhidden -bool true

# Enable debug menu in Safari
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

# Enable debug menu in Mac App Store
defaults write com.apple.appstore ShowDebugMenu -bool true

# TextEdit
defaults write com.apple.TextEdit TabWidth -int 4

# CrashReporter
defaults write com.apple.CrashReporter DialogType none
