#!/bin/bash

# shell
alias help="$HOME/.dotfiles/bin/help"
alias ll="ls -l"
alias la="ls -Al"
alias du="du -h"
alias df="df -h"
alias host="host -a"

# bash
alias resource="source $HOME/.bashrc"
alias rmfunction="unset -f"
alias rmalias="unalias"
alias rmenv="unset -v"

# perl
alias calc="perl -wlne 'print eval;'"

# tar
alias tgz="tar -czf"
alias untgz="tar -xzvf"
alias untbz="tar -xjvf"
alias untar="tar -xvf"

# ls
if [ "$(uname -s)" = "Darwin" ]; then
    alias ls="ls -phGO"
elif [ "$(uname -s)" = "Linux" ]; then
    alias ls="ls -ph --color"
elif [ "$(uname -s)" = "FreeBSD" ]; then
    alias ls="ls -phG"
elif [ "$(uname -s)" = "OpenBSD" ]; then
    alias ls="ls -ph"
elif [ "$(uname -s)" = "SunOS" ]; then
    alias ls="ls -p"
fi

# grep
alias grepi="grep --ignore-case"

# less
alias less="less-highlight"

# ps
if [ "$(uname -s)" = "Darwin" ]; then
    alias _psme="command ps -x -ww -o 'pid,%cpu,%mem,command'"
    alias _psall="command ps -ax -ww -o 'pid,user,%cpu,%mem,command'"
elif [ "$(uname -s)" = "Linux" ]; then
    alias _psme="command ps x -ww -o 'pid,%cpu,%mem,command'"
    alias _psall="command ps ax -ww -o 'pid,user,%cpu,%mem,command'"
elif [ "$(uname -s)" = "FreeBSD" ]; then
    alias _psme="command ps -x -ww -o 'pid,%cpu,%mem,command'"
    alias _psall="command ps -ax -ww -o 'pid,user,%cpu,%mem,command'"
elif [ "$(uname -s)" = "OpenBSD" ]; then
    alias _psme="command ps -x -ww -o 'pid,%cpu,%mem,command'"
    alias _psall="command ps -ax -ww -o 'pid,user,%cpu,%mem,command'"
elif [ "$(uname -s)" = "SunOS" ]; then
    alias _psme="command ps -o 'pid,pcpu,pmem,args'"
    alias _psall="command ps -e -o 'pid,user,pcpu,pmem,args'"
fi

if [ "$(uname -s)" = "Darwin" ]; then
    alias ps="_psme | grep -v '(/System/Library/|/Applications/)' | sort -n"
    alias psv="_psme | grep -v '(/System/Library/)' | sort -n"
    alias psvv="_psme | sort -n"
    alias psa="_psall | grep -v '(/System/Library/|/Applications/)' | sort -n"
    alias psav="_psall | grep -v '(/System/Library/)' | sort -n"
    alias psavv="_psall | sort -n"
else
    alias ps="_psme | sort -n"
    alias psv="ps"
    alias psvv="ps"
    alias psa="_psall | sort -n"
    alias psav="psa"
    alias psavv="psa"
fi

alias psg="psavv | grepi"

# top
if [ "$(uname -s)" = "Darwin" ]; then
    alias top="top -s 1 -S -u"
elif [ "$(uname -s)" = "Linux" ]; then
    alias top="top -d 1"
elif [ "$(uname -s)" = "FreeBSD" ]; then
    alias top="top -s 1"
elif [ "$(uname -s)" = "OpenBSD" ]; then
    alias top="top -s 1"
elif [ "$(uname -s)" = "SunOS" ]; then
    alias top="top -s 1"
fi

# HFS commands
if [ -x "$(which hfsdata 2>/dev/null)" ]; then
    alias lscomment="hfsdata -o"
    alias lscreator="hfsdata -C"
    alias lskind="hfsdata -k"
    alias lslabel="hfsdata -L"
    alias lstype="hfsdata -T"
fi

if [ -x "$(which setfcomment 2>/dev/null)" ]; then
    alias setcomment="setfcomment"
fi

if [ -x "$(which setfctypes 2>/dev/null)" ]; then
    alias settype="settype"
    alias setcreator="setcreator"
fi

if [ -x "$(which setfflags 2>/dev/null)" ]; then
    alias sethidden="setfflags -i true"
    alias setunhidden="setfflags -i false"
fi

# WiFi
if [ "$(uname -s)" = "Darwin" ]; then
    alias airport="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport"
fi
