#!/bin/bash

if [ -z "$PS1" ]; then
    return
fi

# git
source "$HOME/.dotfiles/bash/contrib/git_completion"

function _git_cli() {
    if [ "$prev" = "cli" ]; then
        __gitcomp_nl "$(git-cli --completion)"
        return
    fi

    local command argindex

    if [ "${words[1]}" = "${COMP_WORDS[1]}" ]; then
        command="${COMP_WORDS[2]}"
        argindex=3
    else
        command="${COMP_WORDS[1]}"
        argindex=2
    fi

    local type="$(git-cli --completion "$command")"

    if [ -z "$type" ]; then
        return
    fi

    case "$type" in
        anyfiles)
            __git_complete_index_file "--others --directory"
            ;;

        untrackedfiles)
            __git_complete_index_file "--others --modified --directory --no-empty-directory"
            ;;

        trackedfiles)
            __git_complete_index_file "--cached"
            ;;

        trackedfileandbranch)
            if [ $cword = $argindex ]; then
                __git_complete_index_file "--cached"
            else
                __gitcomp_nl "$(__git_heads)"
            fi
            ;;

        commit)
            ;;

        branch)
            __gitcomp_nl "$(__git_heads)"
            ;;

        logfilter)
            __git_complete_index_file "--cached"
            ;;

    esac
}

# bash
version=${BASH_VERSION%.*}
major=${version%.*}
minor=${version#*.}

if [ $major -gt 4 ] || [ $major -eq 4 -a $minor -ge 1 ]; then
    source "$HOME/.dotfiles/bash/contrib/completion-2.1/bash_completion"
else
    source "$HOME/.dotfiles/bash/contrib/completion-1.1/bash_completion"
fi
