#!/bin/bash

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export LESSCHARSET="utf-8"
export MAILCHECK="0"

export PAGER="less-highlight"
export MANPAGER="less"

export LESS="-F -i -M -R -X -x4"

if [ -n "$LINES" ]; then
    export LESS="$LESS -z-$(expr $LINES / 2)"
fi

export LSCOLORS="cxGxahahFxExExHFHGHCHC"
export LS_COLORS="di=32;40:ln=1;36;40:so=0;47:pi=0;47:ex=1;35;40:bd=1;34;40:cd=1;34;40:su=1;37;1;45:sg=1;37;1;46:tw=1;37;1;42:ow=1;37;1;42:"
export HISTIGNORE="&"

if [ -x "$(which vim 2>/dev/null)" ]; then
    export EDITOR="vim"
else
    export EDITOR="vi"
fi

export PERL_MB_OPT="--install_base \"$HOME/.dotfiles/local/perl5\""
export PERL_MM_OPT="INSTALL_BASE=$HOME/.dotfiles/local/perl5"
export PERL5LIB="$HOME/.dotfiles/perl5/lib/perl5:$HOME/.dotfiles/local/perl5/lib/perl5"

export GEM_HOME="$HOME/.dotfiles/local/ruby-gems"

export PYTHONPATH="$HOME/.dotfiles/local/python/lib/python2.7/site-packages"

if [ -d "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" ]; then
    export SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
fi
