# bash/bashrc

if [ -z "$PS1" ]; then
    return
fi

if [ -f "/etc/bashrc" ]; then
    source "/etc/bashrc"
fi

if [ -f "$HOME/.bash_local" ]; then
    source "$HOME/.bash_local"
fi

source "$HOME/.dotfiles/bash/bash_config"
source "$HOME/.dotfiles/bash/bash_path"
source "$HOME/.dotfiles/bash/bash_env"
source "$HOME/.dotfiles/bash/bash_alias"
source "$HOME/.dotfiles/bash/bash_completion"
source "$HOME/.dotfiles/bash/bash_git_completion"
source "$HOME/.dotfiles/bash/bash_git_prompt"

for i in $(find "$HOME/.dotfiles/bash/functions" -type f -maxdepth 1); do
    source "$i"
done
