#!/bin/bash

# Shell search path
PATH0="/bin:/sbin:."

test -d "/usr/sbin" && PATH0="/usr/sbin:$PATH0"
test -d "/usr/bin" && PATH0="/usr/bin:$PATH0"
test -d "/usr/libexec" && PATH0="/usr/libexec:$PATH0"

if [ -n "$DISPLAY" ]; then
    test -d "/usr/X11R6" && PATH0="/usr/X11R6/bin:$PATH0"
fi

test -d "/usr/local/wired" && PATH0="/usr/local/wired:$PATH0"

test -d "/opt/aws/bin" && PATH0="/opt/aws/bin:$PATH0"
test -d "/opt/homebrew/bin" && PATH0="/opt/homebrew/bin:$PATH0"

test -d "$HOME/.local/bin" && PATH0="$HOME/.local/bin:$PATH0"

if [ "$(uname -s)" = "Darwin" ]; then
    xcodepath=$(xcode-select -p 2>/dev/null)

    if [ "$xcodepath" ]; then
        test -d "$xcodepath/usr/bin" && PATH0="$xcodepath/usr/bin:$PATH0"
    fi

    test -d "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support" && PATH0="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support:$PATH0"
fi

test -d "/usr/local/sbin" && PATH0="/usr/local/sbin:$PATH0"
test -d "/usr/local/bin" && PATH0="/usr/local/bin:$PATH0"
test -d "/opt/local/sbin" && PATH0="/opt/local/sbin:$PATH0"
test -d "/opt/local/bin" && PATH0="/opt/local/bin:$PATH0"

test -d "/opt/aws/bin" && PATH0="/opt/aws/bin:$PATH0"

test -d "/opt/homebrew/bin" && PATH0="/opt/homebrew/bin:$PATH0"
test -d "/opt/homebrew/opt/ruby/bin" && PATH0="/opt/homebrew/opt/ruby/bin:$PATH0"

test -d "$HOME/.dotfiles/bin" && PATH0="$HOME/.dotfiles/bin:$PATH0"
test -d "$HOME/.dotfiles/git/bin" && PATH0="$HOME/.dotfiles/git/bin:$PATH0"
test -d "$HOME/.dotfiles/local/bin" && PATH0="$HOME/.dotfiles/local/bin:$PATH0"
test -d "$HOME/.dotfiles/local/python/bin" && PATH0="$HOME/.dotfiles/local/python/bin:$PATH0"
test -d "$HOME/.dotfiles/local/ruby-gems/bin" && PATH0="$HOME/.dotfiles/local/ruby-gems/bin:$PATH0"

export PATH="$PATH0"

# Man pages search path
MANPATH_MAP0="."

#test -d "/opt/homebrew/manpages" && MANPATH_MAP0="/opt/homebrew/manpages:$MANPATH_MAP0"
#test -d "/usr/local/Homebrew/manpages" && MANPATH_MAP0="/usr/local/Homebrew/manpages:$MANPATH_MAP0"
test -d "$HOME/.dotfiles/local" && MANPATH_MAP0="$HOME/.dotfiles/local:$MANPATH_MAP0"

export MANPATH_MAP="$MANPATH_MAP0"

# Directory shortcuts
CDMAP0="dot:$HOME/.dotfiles"

if [ "$(uname -s)" = "Darwin" ]; then
    CDMAP0="f:+finder-current-directory;$CDMAP0"
    CDMAP0="x:+xcode-current-directory;$CDMAP0"
fi

export CDMAP="$CDMAP0"
