#!/bin/bash

if [ -z "$PS1" ]; then
    return
fi

# Increase size of history
export HISTSIZE="100000"
export HISTFILESIZE="100000"

# After each command, append to history and reread it
if [ "$TERM_PROGRAM" = "Apple_Terminal" ]; then
    export PROMPT_COMMAND="history -a; history -c; history -r; update_terminal_cwd"
else
    export PROMPT_COMMAND="history -a; history -c; history -r"
fi

# Append to history instead of overwriting
shopt -s histappend

# Notify about background job statuses immediately
set -o notify

# Enable extensive glob patterns
shopt -s extglob

# Disable ! style history substitution
set +H

# Bind up/down to history search
bind '"[A":history-search-backward'
bind '"[B":history-search-forward'
