#!/bin/bash

function _prompt_path() {
    local IFS="/"

    if [ "$PWD" = "/" ]; then
        echo -n "/"
        return
    fi

    path="${PWD/$HOME/~}"
    components=($path)
    number=1

    for i in ${components[@]}; do
        result+=$(printf "$1" "$i")

        if [ $number -lt ${#components[@]} ]; then
            result+=$(printf "$2" "/")
        fi

        number=$(expr $number + 1)
    done

    echo -en "$result"
}

GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWDIRTYSTATE="1"
GIT_PS1_STATESEPARATOR=""

source "$HOME/.dotfiles/bash/contrib/git_prompt"

PS_ID="\[$cbwhi\]\u@\h\[$cres\]"
PS_PATH='$(_prompt_path "\[$cbgre\]%s\[$cres\]" "\[$cbwhi\]%s\[$cres\]")'
PS_GIT='$(__git_ps1 " \[$cblu\]%s\[$cres\]")'
PS_ARROW="\[$cbwhi\]>\[$cres\]"

export PS1="$PS_ID $PS_PATH$PS_GIT$PS_ARROW "
