#!/bin/bash

export LESSCHARSET="latin1"
export MAILCHECK="0"
export PAGER="less"
export LESS="-imrX"
export LSCOLORS="cxGxahahFxExExHFHGHCHC"
export LS_COLORS="di=32;40:ln=1;36;40:so=0;47:pi=0;47:ex=1;35;40:bd=1;34;40:cd=1;34;40:su=1;37;1;45:sg=1;37;1;46:tw=1;37;1;42:ow=1;37;1;42:"
export HISTIGNORE="&"

if [ -x "$(which vim 2>/dev/null)" ]; then
    export EDITOR="vim"
else
    export EDITOR="vi"
    echo "warning: 'vim' is not available, use 'vi' instead"
fi

export PERL_MB_OPT="--install_base \"$HOME/.dotfiles/local/perl5\""
export PERL_MM_OPT="INSTALL_BASE=$HOME/.dotfiles/local/perl5"
export PERL5LIB="$HOME/.dotfiles/local/perl5/lib/perl5"

export GEM_HOME="$HOME/.dotfiles/local/ruby-gems"
