#!/bin/bash

if [ -z "$PS1" ]; then
    return
fi

if [ -f "/etc/bashrc" ]; then
    source "/etc/bashrc"
fi

for i in "$HOME/.bash_local_"*; do
    if [ -f "$i" ]; then
        source $i
    fi
done

source "$HOME/.dotfiles/bash/bash_prompt"
source "$HOME/.dotfiles/bash/bash_config"
source "$HOME/.dotfiles/bash/bash_path"
source "$HOME/.dotfiles/bash/bash_env"
source "$HOME/.dotfiles/bash/bash_alias"
source "$HOME/.dotfiles/bash/bash_completion"

for i in "$HOME/.dotfiles/bash/functions"/*; do
    source "$i"
done
